.TH DPARALLEL "1" "June 2013" "dparallel 0.0.1" "Distributed Command Tool"

.SH "NAME"
dparallel \- run commands in parallel on a distributed system.

.SH "SYNOPSIS"

.TP
\fB\-h\fR, \fB\-\-help\fR
Print a brief message listing the \fBdparallel\fR options and usage.

.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.

.SH "AUTHORS"
Jon Bringhurst <jon@bringhurst.org>
