#!/bin/bash

. /usr/local/tools/dotkit/init.sh
use mvapich2-gnu

set -x

INCLUDES="-I../../install/include -I../dtar_ext/include"
LIBS="-L../../install/lib -L../dtar_ext/lib -lbayer -lcircle -larchive -ldtcmp -llwgrp"
OPT="-g -O0"
pushd src
  mpicc -o copy.o -c copy.c $OPT $INCLUDES
  mpicc -o helper.o -c helper.c $OPT $INCLUDES
  mpicc -o dtar.o -c dtar.c $OPT $INCLUDES
  mpicc -o dtar dtar.o copy.o helper.o $LIBS
popd

exit 0;

#./buildme_dependencies

export DTAR_EXT=`pwd`/dtar_ext
export LD_LIBRARY_PATH=`pwd`/../install/lib:$DTAR_EXT/lib:$LD_LIBRARY_PATH

rm -rf build
mkdir -p build
pushd build
  cmake -DCMAKE_BUILD_TYPE=Debug ..
  make
popd
