include: [component: $CI_SERVER_FQDN/lc-components/id_tokens/id_tokens-component@main]
      
build-job:
  tags:
    - oslic
    - shell
  script:
    - echo "Starting build stage for mpifileutils"
  stage: build
  script:
    - pwd
    - module load openmpi-gnu
    - cd ..
    - ./mpifileutils/scripts/prepmfubuild.sh
    - rm -fr build
    - mkdir build
    - cd build
    - cmake ../mpifileutils -DWITH_DTCMP_PREFIX=../install \n
                            -DWITH_LibCircle_PREFIX=../install \n
                            -DWITH_LibArchive_PREFIX=../install \n
                            -DCMAKE_INSTALL_PREFIX=../install
    - make -j install

# Do not delete next jobs and stages.
# Used as place holder for next step
# for CD/CI LLNL

test-job1:
  tags:
    - oslic
    - shell
  script:
    - echo "Hello there!!"
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  tags:
    - oslic
    - shell
  script:
    - echo "Hello there!!"
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  tags:
    - oslic
    - shell
  script:
    - echo "Hello there!!"
  stage: deploy
  script:
    - echo "This job deploys something from the branch."
  environment: production


