#!/bin/bash

##################
# Load mpicc and mpicxx into $PATH
##################

#. /usr/share/[mM]odules/init/bash
#module load mvapich2-gnu-psm/1.7

#. /usr/local/tools/dotkit/init.sh
#use mvapich2-gnu

# MVAPICH
#curdir=`pwd`
#export PATH="${curdir}/mvapich2/install/bin:$PATH"

# Open MPI
#curdir=`pwd`
#export PATH="${curdir}/openmpi/install/bin:$PATH"

##################
# Build software
##################

set -x

OPT="-g -O0"

installdir=`pwd`/install

mkdir -p deps
cd deps

# fetch dependencies
if [ ! -d libcircle.git ] ; then
  git clone git://github.com/hpc/libcircle.git libcircle.git
fi
if [ ! -d lwgrp.git ] ; then
  git clone git://github.com/hpc/lwgrp.git lwgrp.git
fi
if [ ! -d dtcmp.git ] ; then
  git clone git://github.com/hpc/dtcmp.git dtcmp.git
fi

if [ ! -d libcircle.git ]; then
  echo "missing libcircle"
  exit 1
fi
if [ ! -d lwgrp.git ]; then
  echo "missing lwgrp"
  exit 1
fi
if [ ! -d dtcmp.git ]; then
  echo "missing dtcmp"
  exit 1
fi

# build dependencies
pushd libcircle.git
  export CFLAGS=${OPT}
  ./configure --prefix=$installdir && \
  make VERBOSE=1 && \
  make VERBOSE=1 install
  if [ $? -ne 0 ]; then
    echo "failed to configure, build, or install libcircle"
    exit 1
  fi
popd

pushd lwgrp.git
#  make distclean
#  ./autogen.sh
  export CFLAGS=${OPT}
  ./configure --prefix=${installdir} && \
  make && \
  make install
  if [ $? -ne 0 ]; then
    echo "failed to configure, build, or install liblwgrp"
    exit 1
  fi
popd

pushd dtcmp.git
#  make distclean
#  ./autogen.sh
  export CFLAGS=${OPT}
  ./configure --prefix=${installdir} --with-lwgrp=${installdir} && \
  make && \
  make install
  if [ $? -ne 0 ]; then
    echo "failed to configure, build, or install libdtcmp"
    exit 1
  fi
popd
