#!/bin/bash

. /usr/local/tools/dotkit/init.sh
use mvapich2-gnu-2.2

set -x

topdir=`pwd`
installdir=$topdir/install

export PATH="${topdir}/autotools/install/bin:$PATH"

./autogen.sh

rm -rf build
mkdir -p build
cd build

export PKG_CONFIG_PATH="${installdir}/lib/pkgconfig"

# TODO: avoid this step
# necessary so configure test of dtcmp links with MPI
export CC=mpicc

# hack to get things to build after common library
export CFLAGS="-g -O0 -I${topdir}/src/common -DDCOPY_USE_XATTRS"
export LDFLAGS="-Wl,-rpath,${topdir}/install/lib -L${topdir}/install/lib -lcircle"

../configure \
  --enable-lustre \
  --enable-experimental \
  --prefix=$installdir \
  --disable-silent-rules \
  --with-dtcmp=$installdir && \
make VERBOSE=1 && \
make VERBOSE=1 install
if [ $? -ne 0 ] ; then
  echo "failed to configure, build, or install file utils"
  exit 1
fi
