#!/bin/bash

. /usr/local/tools/dotkit/init.sh
use mvapich2-gnu

set -x

export topdir=`pwd`
export installdir=$topdir/install
export PATH="${topdir}/autotools/install/bin:$PATH"

./autogen.sh

export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:${installdir}/lib/pkgconfig"

# TODO: avoid this step
# necessary so configure test of dtcmp links with MPI
export CC=mpicc

# hack to get things to build after common library
export CFLAGS="-I${topdir}/src/common -DDCOPY_USE_XATTRS"
export LDFLAGS="-Wl,-rpath,${topdir}/install/lib -L${topdir}/install/lib -lcircle"


#./configure \
#  --enable-lustre \
#  --prefix=$installdir \
#  --disable-silent-rules \
#  --with-dtcmp=$installdir && \
./configure --enable-dist && \
make dist && \
make rpm
if [ $? -ne 0 ] ; then
  echo "failed to configure, build, or build file utils rpm"
  exit 1
fi
