#!/bin/bash

. /usr/local/tools/dotkit/init.sh
use mvapich2-gnu

set -x

topdir=`pwd`
installdir=$topdir/install

export PATH="${topdir}/autotools/install/bin:$PATH"

./autogen.sh

rm -rf build
mkdir -p build
cd build

export PKG_CONFIG_PATH="${installdir}/lib/pkgconfig"

# TODO: avoid this step
# necessary so configure test of dtcmp links with MPI
export CC=mpicc

# hack to get things to build after common library
export CFLAGS="-I${topdir}/src/common -DDCOPY_USE_XATTRS"
export LDFLAGS="-Wl,-rpath,${topdir}/install/lib -L${topdir}/install/lib -lcircle"

make distclean

../configure \
  --prefix=$installdir \
  --disable-silent-rules \
  --with-dtcmp=$installdir
#../configure \
#  --prefix=/usr/local/fileutils
if [ $? -ne 0 ] ; then
  echo "failed to configure"
  exit 1
fi

make dist
if [ $? -ne 0 ] ; then
  echo "failed to make dist"
  exit 1
fi

make distcheck
if [ $? -ne 0 ] ; then
  echo "failed to make distcheck"
  exit 1
fi

mv *.tar.gz ../.
