#!/bin/csh
#SBATCH -A cbronze   ## bank
#SBATCH -N 1         ## number of nodes
#SBATCH -t 10:00     ## length of run in hr:min
#SBATCH -p pdebug    ## queue (pdebug or pbatch)
#SBATCH -o outdf   ## name of output file
#SBATCH -e errdf   ## name of error file
#SBATCH --export=ALL ## verbose to 

# set directory to run in
cd /p/lustre2/levatin/dfile3
# next line may not be needed.  it sets the path to shared libraries needed by your code, if any
#setenv LD_LIBRARY_PATH /usr/tce/packages/mpifileutils/mpifileutils-0.8/install/lib:/usr/tce/packages/mpifileutils/mpifileutils-0.8/lib
setenv LD_LIBRARY_PATH /usr/tce/packages/mpifileutils/mpifileutils-0.9/install/lib:/usr/tce/packages/mpifileutils/mpifileutils-0.9/lib64
# set full path to code to run
set codepath = /usr/workspace/levatin/nfs/tmp2/moody2/mpifileutils/src/dfilemaker/dfilemaker
# parallel run with 5 cpus, do not need srun if serial code
time srun  -n5  $codepath    -i 12 -f true -s 4mb-10mb -n 500-1000 
