#!/bin/bash

##################
# Load mpicc and mpicxx into $PATH
##################

#. /usr/share/[mM]odules/init/bash
#module load mvapich2-gnu-psm/1.7

#. /usr/local/tools/dotkit/init.sh
#use mvapich2-gnu

curdir=`pwd`
export PATH="${curdir}/mvapich2/install/bin:$PATH"

##################
# Build software
##################

set -x

OPT="-g -O0"

installdir=`pwd`/install
rm -rf $installdir

# fetch dependencies
if [ ! -f libcircle.git ] ; then
  git clone git://github.com/hpc/libcircle.git libcircle.git
fi
if [ ! -f lwgrp.git ] ; then
  git clone git://github.com/hpc/lwgrp.git lwgrp.git
fi
if [ ! -f dtcmp.git ] ; then
  git clone git://github.com/hpc/dtcmp.git dtcmp.git
fi

# build dependencies
pushd libcircle.git
  export CFLAGS=${OPT}
  ./configure --prefix=$installdir
  make clean
  make VERBOSE=1
  make VERBOSE=1 install
popd

pushd lwgrp.git
#  make distclean
#  ./autogen.sh
  export CFLAGS=${OPT}
  ./configure --prefix=${installdir}
  make clean
  make
  make install
popd

pushd dtcmp.git
#  make distclean
#  ./autogen.sh
  export CFLAGS=${OPT}
  ./configure --prefix=${installdir} --with-lwgrp=${installdir}
  make clean
  make
  make install
popd
