FUNCTION(MFU_ADD_TOOL name)

  ADD_EXECUTABLE(${name} ${name}.c)
  TARGET_LINK_LIBRARIES(${name} mfu)
  SET_TARGET_PROPERTIES(${name} PROPERTIES C_STANDARD 99)
  INSTALL(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/${name} DESTINATION ${CMAKE_INSTALL_BINDIR})

ENDFUNCTION(MFU_ADD_TOOL name)
