FUNCTION(MFU_ADD_TOOL name)

  ADD_EXECUTABLE(${name} ${name}.c)
  TARGET_LINK_LIBRARIES(${name} mfu m)
  SET_TARGET_PROPERTIES(${name} PROPERTIES C_STANDARD 99)
  INSTALL(TARGETS ${name} DESTINATION ${CMAKE_INSTALL_BINDIR})

ENDFUNCTION(MFU_ADD_TOOL name)
