.TH DCP 1 "" 
.SH NAME
.PP
dcp \- distributed copy

.SH SYNOPSIS
.TP
.B dcp [OPTION] SOURCE DEST
.B dcp [OPTION] SOURCE... DIRECTORY

.SH DESCRIPTION
.PP
Parallel MPI application to recursively copy files and directories.
.PP
dcp is a file copy tool in the spirit of \f[I]cp(1)\f[] that evenly
distributes work across a large cluster without any centralized state.
It is designed for copying files which are located on a distributed
parallel file system.
The method used in the file copy process is a self\-stabilization
algorithm which enables per\-node autonomous processing and a token
passing scheme to detect termination.

.SH OPTIONS
.TP
.B \-d, \-\-debug=\f[I]level\f[]
Specify the level of debug information to output.
Level may be one of: \f[I]fatal\f[], \f[I]err\f[], \f[I]warn\f[],
\f[I]info\f[], or \f[I]dbg\f[].
Increasingly verbose debug levels include the output of less verbose
debug levels.
.TP
.B \-f, \-\-force
Remove existing destination files if creation or truncation fails.
.TP
.B \-p, \-\-preserve
Preserve permissions, ownership, timestamps, and extended attributes of original files.
.TP
.B \-s, \-\-synchronous
Use synchronous read/write calls (i.e., files are opened with O_DIRECT).  This option ensures data is written to disk when command completes.  It may be useful to oversubscribe MPI processes with this option.
.TP
.B \-v, \-\-version
Print version information and exit.
.TP
.B \-h, \-\-help
Print a brief usage message.

.SH RESTRICTIONS
.PP
If a long-running copy is interrupted, one should delete the target directory with drm
and rerun dcp.
.PP
To ensure the copy was successful, one should run dcmp after dcp completes, especially if the -s option was not used with dcp.
.PP
The maximum supported filename length for any file transfered is
approximately 4068 characters.
This may be less than the number of characters that your operating
system supports.

.SH EXAMPLES
.TP
(1) To copy dir1 as dir2:
.TP
.nf
mpirun -np 128 dcp /source/dir1 /dest/dir2
.fi
.TP
(2) To copy contents of dir1 into dir2:
.PP
.nf
mkdir /dest/dir2
mpirun -np 128 dcp /source/dir1/* /dest/dir2
.fi

.SH SEE ALSO
.TP
dcmp, drm, and dwalk.

.PP
Source code and documentation for the FileUtils suite may be downloaded from:
.PP
<http://fileutils.io>
